# config file for reading XML data from the FileMaker Server
# the user specified here has read-only access
  :host: 'brugmann.eva.mpg.de' # IP address: 194.94.96.174
  :database: 'Valency'
  :account_name: 'script'
  :password: 'ruby-rfm'
  :ssl: false
  :root_cert: false
  :port: 80 # 443 for SSL
  :timeout: 20
